# action.yml
name: "OpenTelemetry Collector Builder"
description: "Build a custom OpenTelemetry Collector"
inputs:
  manifest-file: # id of input
    description: "Path to the manifest file"
    required: true
    default: "manifest.yaml"
  output-path: # id of input
    description: "Output path"
    required: true
    default: "_build"
outputs:
  collector-file: # id of output
    description: "The generated Collector binary"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.manifest-file }}
    - ${{ inputs.output-path }}
